// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.2
//   protoc               v3.12.4
// source: orders.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Product } from "./products";

export const protobufPackage = "orders";

export interface GetOrderRequest {
  orderId: string;
}

export interface OrderResponse {
  order: Order | undefined;
  items: OrderItem[];
}

export interface Order {
  orderId: string;
  createdAt: string;
  delivered: boolean;
}

export interface OrderItem {
  productId: string;
  quantity: number;
  orderId: string;
  product: Product | undefined;
}

export interface CreateOrderRequest {
  createdAt: string;
  delivered: boolean;
  items: OrderItem[];
}

export const ORDERS_PACKAGE_NAME = "orders";

export interface OrdersServiceClient {
  getOrder(request: GetOrderRequest): Observable<OrderResponse>;

  createOrder(request: CreateOrderRequest): Observable<OrderResponse>;
}

export interface OrdersServiceController {
  getOrder(request: GetOrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  createOrder(request: CreateOrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;
}

export function OrdersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getOrder", "createOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrdersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrdersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDERS_SERVICE_NAME = "OrdersService";
